### ISSUE TITLE
How to analyze multiple source files?

### ISSUE THREAD

**Issue by Ychame** [TDacik/Deadlock#1]

**Comment by Y-chav** [comment]
The Usage only shows the process of analyzing a single file. Can this tool analyze a project with multiple source files?

**Comment by TDacik** [comment]
Yes, it is possible by running the tool as
`frama-c -deadlock source1.c source2.c source3.c` ...

In general, the usage is mostly the same as for other Frama-C's plugins, so you may also find useful this [manual](https://frama-c.com/download/frama-c-user-manual.pdf).
